//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASE.GreySentimentAnalysis.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASE.GreySentimentAnalysis.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (:,0.406,0.0938,0.55,0.0938,0.55
        ///):,-0.296,0.1688,-0.45,-0.45,0.1688
        ///:(,-0.454,-0.4296,-0.475,-0.475,-0.4296
        ///:&apos;(,-0.562,-0.3488,-0.55,-0.562,-0.3488
        ///:&apos;),0.218,-0.014,0.575,-0.014,0.575
        ///:/,-0.374,-0.0624,-0.35,-0.374,-0.0624
        ///:],0.422,0.1648,0.55,0.1648,0.55
        ///:|,-0.062,-0.1218,-0.1,-0.1218,-0.062
        ///:d,-0.078,0.2562,0.575,-0.078,0.575
        ///:-d,-0.156,-0.0096,0.575,-0.156,0.575
        ///:o,0.032,-0.0538,-0.1,-0.1,0.032
        ///:p,0.344,0.0926,0.25,0.0926,0.35
        ///:s,-0.094,-0.0746,-0.3,-0.3,-0.0746
        ///;),0.312,0.1414,0.225,0.1414 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreySentimentLexicon {
            get {
                return ResourceManager.GetString("GreySentimentLexicon", resourceCulture);
            }
        }
    }
}
